id: '1763164901310'
name: Alarm
entities:
  light.bedroom_lamp:
    min_color_temp_kelvin: 2127
    max_color_temp_kelvin: 6535
    min_mireds: 153
    max_mireds: 470
    supported_color_modes:
      - color_temp
      - hs
      - xy
    color_mode: color_temp
    brightness: 255
    color_temp_kelvin: 6535
    color_temp: 153
    hs_color:
      - 54.768
      - 1.6
    rgb_color:
      - 255
      - 255
      - 251
    xy_color:
      - 0.325
      - 0.333
    friendly_name: Bedroom Lamp
    supported_features: 32
    state: 'on'
icon: mdi:alarm-light
metadata: {}
