id: '1763164901310'
name: Alarm
entities:
  light.bedroom_lamp:
    state: 'on'
    brightness: 255
    color_temp_kelvin: 6535
  light.bedroom_overhead_left:
    state: 'on'
    brightness: 255
    color_temp_kelvin: 6535
  light.bedroom_overhead_right:
    state: 'on'
    brightness: 255
    color_temp_kelvin: 6535
icon: mdi:alarm-light
metadata: {}
