id: '1763159661461'
name: Bedroom lights on
entities:
  light.bedroom_lamp:
    state: 'on'
    brightness: 107
    color_temp_kelvin: 3597
  light.bedroom_overhead_left:
    state: 'on'
    brightness: 107
    color_temp_kelvin: 3597
  light.bedroom_overhead_right:
    state: 'on'
    brightness: 107
    color_temp_kelvin: 3597
icon: mdi:lamp
metadata: {}
