id: '1763159704911'
name: Bedroom lights off
entities:
  light.bedroom_lamp:
    state: 'off'
  light.bedroom_overhead_left:
    state: 'off'
  light.bedroom_overhead_right:
    state: 'off'
icon: mdi:lamp-outline
metadata: {}
