id: '1762730794917'
name: Cooking
entities:
  light.island_bulb:
    state: 'on'
    brightness: 255
    color_temp_kelvin: 5025
  light.sink_bulb:
    state: 'on'
    brightness: 255
    color_temp_kelvin: 5025
  light.hue_lightstrip_plus_1:
    state: 'on'
    brightness: 255
    color_temp_kelvin: 5025
  switch.kitchen_counter_switch:
    state: 'on'
icon: mdi:toaster-oven
metadata: {}
