id: '1763238409802'
name: Daytime potty
entities:
  light.bathroom_lamp:
    min_color_temp_kelvin: 2127
    max_color_temp_kelvin: 6535
    min_mireds: 153
    max_mireds: 470
    supported_color_modes:
      - color_temp
      - hs
      - xy
    color_mode: color_temp
    brightness: 107
    color_temp_kelvin: 2127
    color_temp: 470
    hs_color:
      - 30.069
      - 88.053
    rgb_color:
      - 255
      - 143
      - 30
    xy_color:
      - 0.586
      - 0.387
    friendly_name: Bathroom Lamp
    supported_features: 32
    state: 'on'
  light.bathroom_strip:
    min_color_temp_kelvin: 2000
    max_color_temp_kelvin: 6535
    min_mireds: 153
    max_mireds: 500
    supported_color_modes:
      - color_temp
      - xy
    color_mode: color_temp
    brightness: 192
    color_temp_kelvin: 2000
    color_temp: 500
    hs_color:
      - 30.601
      - 94.547
    rgb_color:
      - 255
      - 137
      - 14
    xy_color:
      - 0.598
      - 0.383
    mode: normal
    dynamics: none
    friendly_name: Bathroom strip
    supported_features: 40
    state: 'on'
icon: mdi:toilet
metadata: {}
