id: '1762816501938'
name: Eating
entities:
  light.island_bulb:
    state: 'off'
  light.sink_bulb:
    state: 'off'
  light.hue_lightstrip_plus_1:
    state: 'off'
  light.living_room_light:
    state: 'on'
    brightness: 63
    color_temp_kelvin: 2127
  switch.kitchen_counter_switch:
    state: 'off'
icon: mdi:food-fork-drink
metadata: {}
