id: '1762899387811'
name: Kitchen chill
entities:
  light.kitchen:
    min_color_temp_kelvin: 2000
    max_color_temp_kelvin: 6535
    min_mireds: 153
    max_mireds: 500
    supported_color_modes:
      - color_temp
      - xy
    color_mode: color_temp
    brightness: 128
    color_temp_kelvin: 2000
    color_temp: 500
    hs_color:
      - 30.601
      - 94.547
    rgb_color:
      - 255
      - 137
      - 14
    xy_color:
      - 0.598
      - 0.383
    is_hue_group: true
    hue_scenes: []
    hue_type: room
    lights:
      - Sink bulb
      - Kitchen strip
      - Island bulb
    entity_id:
      - light.island_bulb
      - light.hue_lightstrip_plus_1
      - light.sink_bulb
    dynamics: false
    icon: mdi:lightbulb-group
    friendly_name: Kitchen
    supported_features: 40
    state: 'on'
  switch.kitchen_counter_switch:
    device_class: outlet
    friendly_name: Kitchen counter switch
    state: 'off'
icon: mdi:toaster-oven
metadata: {}
