id: '1763159062569'
name: Kitchen Off
entities:
  light.kitchen:
    min_color_temp_kelvin: 2000
    max_color_temp_kelvin: 6535
    min_mireds: 153
    max_mireds: 500
    supported_color_modes:
      - color_temp
      - xy
    color_mode: null
    brightness: null
    color_temp_kelvin: null
    color_temp: null
    hs_color: null
    rgb_color: null
    xy_color: null
    is_hue_group: true
    hue_scenes: []
    hue_type: room
    lights:
      - Sink bulb
      - Kitchen strip
      - Island bulb
    entity_id:
      - light.island_bulb
      - light.hue_lightstrip_plus_1
      - light.sink_bulb
    dynamics: false
    icon: mdi:lightbulb-group
    friendly_name: Kitchen
    supported_features: 40
    state: 'off'
  switch.kitchen_counter_switch:
    device_class: outlet
    friendly_name: Kitchen counter switch
    state: 'off'
icon: mdi:lightbulb-group-off
metadata: {}
