id: '1762644522443'
name: Lights out
entities:
  light.island_bulb:
    min_color_temp_kelvin: 2000
    max_color_temp_kelvin: 6535
    min_mireds: 153
    max_mireds: 500
    effect_list:
      - 'off'
      - candle
      - fire
      - prism
      - sparkle
      - opal
      - glisten
      - underwater
      - cosmos
      - sunbeam
      - enchant
      - sunrise
      - sunset
    supported_color_modes:
      - color_temp
      - xy
    effect: null
    color_mode: null
    brightness: null
    color_temp_kelvin: null
    color_temp: null
    hs_color: null
    rgb_color: null
    xy_color: null
    mode: normal
    dynamics: none
    friendly_name: Island bulb
    supported_features: 44
    state: 'off'
  light.hue_lightstrip_plus_1:
    min_color_temp_kelvin: 2000
    max_color_temp_kelvin: 6535
    min_mireds: 153
    max_mireds: 500
    effect_list:
      - 'off'
      - candle
      - fire
      - prism
      - sparkle
      - opal
      - glisten
    supported_color_modes:
      - color_temp
      - xy
    effect: null
    color_mode: null
    brightness: null
    color_temp_kelvin: null
    color_temp: null
    hs_color: null
    rgb_color: null
    xy_color: null
    mode: normal
    dynamics: none
    friendly_name: Kitchen strip
    supported_features: 44
    state: 'off'
  light.sink_bulb:
    min_color_temp_kelvin: 2000
    max_color_temp_kelvin: 6535
    min_mireds: 153
    max_mireds: 500
    effect_list:
      - 'off'
      - candle
      - fire
      - prism
      - sparkle
      - opal
      - glisten
      - underwater
      - cosmos
      - sunbeam
      - enchant
      - sunrise
      - sunset
    supported_color_modes:
      - color_temp
      - xy
    effect: null
    color_mode: null
    brightness: null
    color_temp_kelvin: null
    color_temp: null
    hs_color: null
    rgb_color: null
    xy_color: null
    mode: normal
    dynamics: none
    friendly_name: Sink bulb
    supported_features: 44
    state: 'off'
  switch.kitchen_counter_switch:
    device_class: outlet
    friendly_name: Kitchen counter switch
    state: 'off'
  light.living_room_light:
    min_color_temp_kelvin: 2127
    max_color_temp_kelvin: 6535
    min_mireds: 153
    max_mireds: 470
    supported_color_modes:
      - color_temp
      - hs
      - xy
    color_mode: null
    brightness: null
    color_temp_kelvin: null
    color_temp: null
    hs_color: null
    rgb_color: null
    xy_color: null
    friendly_name: Living Room Light
    supported_features: 32
    state: 'off'
  light.bedroom_lamp:
    state: 'off'
  light.bedroom_overhead_left:
    state: 'off'
  light.bedroom_overhead_right:
    state: 'off'
icon: mdi:lightbulb-night-outline
metadata: {}
