id: '1763162429554'
name: Nighttime potty
entities:
  light.bathroom_strip:
    min_color_temp_kelvin: 2000
    max_color_temp_kelvin: 6535
    min_mireds: 153
    max_mireds: 500
    supported_color_modes:
      - color_temp
      - xy
    color_mode: xy
    brightness: 26
    color_temp_kelvin:
    color_temp:
    hs_color:
      - 308.125
      - 37.647
    rgb_color:
      - 255
      - 159
      - 242
    xy_color:
      - 0.371
      - 0.2393
    mode: normal
    dynamics: none
    friendly_name: Bathroom strip
    supported_features: 40
    state: 'on'
icon: mdi:led-strip
metadata: {}
