id: '1762711453046'
name: TV Time
entities:
  light.kitchen:
    min_color_temp_kelvin: 2000
    max_color_temp_kelvin: 6535
    min_mireds: 153
    max_mireds: 500
    supported_color_modes:
      - color_temp
      - xy
    color_mode: xy
    brightness: 13
    color_temp_kelvin: null
    color_temp: null
    hs_color:
      - 308.125
      - 37.647
    rgb_color:
      - 255
      - 159
      - 242
    xy_color:
      - 0.371
      - 0.239
    is_hue_group: true
    hue_scenes: []
    hue_type: room
    lights:
      - Sink bulb
      - Kitchen strip
      - Island bulb
    entity_id:
      - light.island_bulb
      - light.hue_lightstrip_plus_1
      - light.sink_bulb
    dynamics: false
    icon: mdi:lightbulb-group
    friendly_name: Kitchen
    supported_features: 40
    state: 'on'
  switch.kitchen_counter_switch:
    device_class: outlet
    friendly_name: Kitchen counter switch
    state: 'off'
  light.living_room_light:
    min_color_temp_kelvin: 2127
    max_color_temp_kelvin: 6535
    min_mireds: 153
    max_mireds: 470
    supported_color_modes:
      - color_temp
      - hs
      - xy
    color_mode: null
    brightness: null
    color_temp_kelvin: null
    color_temp: null
    hs_color: null
    rgb_color: null
    xy_color: null
    friendly_name: Living Room Light
    supported_features: 32
    state: 'off'
  light.bedroom_lamp:
    state: 'off'
  light.bedroom_overhead_left:
    state: 'off'
  light.bedroom_overhead_right:
    state: 'off'
icon: mdi:television
metadata: {}
