id: '1762785763071'
name: Working
entities:
  light.island_bulb:
    state: 'off'
  light.sink_bulb:
    state: 'off'
  light.hue_lightstrip_plus_1:
    state: 'off'
  light.living_room_light:
    state: 'off'
  light.bedroom_lamp:
    state: 'on'
    brightness: 255
    color_temp_kelvin: 5076
  light.bedroom_overhead_left:
    state: 'on'
    brightness: 255
    color_temp_kelvin: 5076
  light.bedroom_overhead_right:
    state: 'on'
    brightness: 255
    color_temp_kelvin: 5076
  switch.kitchen_counter_switch:
    state: 'off'
icon: mdi:laptop
metadata: {}
