id: '1762718598905'
alias: Arriving home
description: "Triggers kitchen presence lighting when arriving home"
triggers:
  - trigger: zone
    entity_id: person.john_allen
    zone: zone.home
    event: enter
conditions: []
actions:
  - action: automation.trigger
    target:
      entity_id: automation.kitchen_presence_lighting
mode: single
