id: '1763162380504'
alias: Potty time
description: Pre-emptively turn on bathroom light at 2:30am for nighttime bathroom visits
triggers:
  - trigger: time
    at: 02:30:00
conditions: []
actions:
  - action: script.bathroom_lights
mode: single
