id: '1763162380504'
alias: Potty time
description: ''
triggers:
  - trigger: time
    at: input_datetime.potty_time
conditions: []
actions:
  - action: scene.turn_on
    metadata: {}
    data: {}
    target:
      entity_id: scene.nighttime_potty
mode: single
