id: '1763165064021'
alias: Trigger alarm
description: 'Triggers alarm lights when lock is unlocked while alarm is enabled'
triggers:
  - trigger: state
    entity_id:
      - lock.nuki_smart_lock
    from:
      - locked
    to:
      - unlocked
conditions:
  - condition: state
    entity_id: input_boolean.alarm_enabled
    state: 'on'
actions:
  - action: scene.turn_on
    target:
      entity_id: scene.alarm
mode: single
